const Articulos = {
    "PixiCam": "camaras",
    "Camara Arduino": "camaras",
    "Camera Creative": "camaras",
    "Camara Logitech 720p": "camaras",
    "Camara Logitech 1080p": "camaras",
    "Micro Gear Motor": "motores",
    "Pololu Motor 12v": "motores",
    "Pololu Motor Encoder 12v": "motores",
    "Ultrasonico": "distancia",
    "Sharp": "distancia",
    "Sharp Larga Distancia": "distancia",
    "Time Of Flight": "distancia",
    "MLX90614": "temperatura",
    "Pressure and Temp Sensor BMP280": "temperatura",
    "Servo HS-452BB": "servo motores",
    "Servo 1711 MG": "servo motores",
    "Servo SM-S3317SR": "servo motores",
    "Servo MG92B": "servo motores",
    "Servo MG995": "servo motores",
    "Servo SG5010": "servo motores",
    "Servo Azul": "servo motores",
    "Servo AR3606HB": "servo motores",
    "Servo SM-S4315R": "servo motores",
    "MicroServo A0090": "servo motores",
    "Servo 1501 MG": "servo motores",
    "Intel Edison": "micros",
    "Arduino Nano": "micros",
    "Arduino 101": "micros",
    "Arduino DUE": "micros",
    "Arduino UNO": "micros",
    "Arduino Mega": "micros",
    "Raspberry Pi 2B": "micros",
    "Arduino Pro Mini": "micros",
    "RaspberryPi Zero": "micros",
    "Llantas Mecanum Lego": "mecanica",
    "Llantas omnidireccionales VEX": "mecanica",
    "Llantas Omnidireccionales Lego": "mecanica",
    "Track & Wheel Set": "mecanica",
    "Garra": "mecanica",
    "Llantas Mecanum Rojas": "mecanica",
    "Llantas Sumo": "mecanica",
    "Acelerometro GY-61": "imu",
    "BNO055": "imu",
    "MPU gy-521": "imu",
    "CMPS 11": "imu",
    "TCRT": "varios",
    "Sensor de Color": "varios",
    "ZX Gesture sensor": "varios",
    "Sound Detector": "varios",
    "Bluetooth Arduino": "varios",
    "TFTLCD Arduino Mega": "varios",
    "Cable Arduino": "varios",
    "Cable Mini USB": "varios",
    "Cable Ethernet": "varios",
    "Matriz Leds 8x8": "varios",
    "LCD 16x2 sin I2C": "varios",
    "Joystick": "varios",
    "gy gps6mv2": "varios",
    "Pelota Infraroja": "varios",
    "Infrared Seeker": "varios",
    "USB Bluetooth Dongle": "varios",
    "RGB Sensor TCS34725": "varios",
    "XY FST": "varios",
    "HM R": "varios",
    "TSOP": "varios",
    "Switches": "electronica",
    "Potenciometros": "electronica",
    "Battery Jack": "electronica",
    "Boton": "electronica",
    "Portapilas AA": "electronica",
    "Conector XT": "electronica",
    "Regulador LM317T": "electronica",
    "Broche Portapilas AA": "electronica",
    "Pila Lipo 11_1V 2200 mAh": "electronica",
    "Pila Lipo 11_1v 3000 mAh": "electronica",
    "Pila Lipo 7_4v 1700mAh": "electronica",
    "Pila Lipo 7_4v 2200mAh": "electronica",
    "Pila Lipo 7_4v 2150mAh": "electronica",
    "Pila Lipo desconocida": "electronica",
    "Logic Level Converter": "electronica",
    "Cargador Pilas Lipoo": "electronica",
    "4 Relay Module": "electronica",
    "Regulador de Voltaje variable": "electronica",
    "BreadBoard power": "electronica",
    "LED RGB": "electronica",
    "Display 7 segmentos": "electronica",
    "TIP31C": "electronica",
    "Driver L298N": "drivers",
    "Motor Shield Seed Studio": "drivers",
    "Adafruit Motor Shield v2": "drivers",
}

export default Articulos