const Articulos = {
    "PixiCam": "camaras",
    "Camara Arduino": "camaras",
    "Micro Gear Motor": "motores",
    "Ultrasonico": "distancia",
    "Sharp": "distancia",
    "MLX90614": "temperatura",
    "Servo HS-452BB": "servo motores",
    "Servo 1711 MG": "servo motores",
    "Servo SM-S3317SR": "servo motores",
    "Servo MG92B": "servo motores",
    "Servo SG5010": "servo motores",
    "Servo Azul": "servo motores",
    "Servo SM-S4315R": "servo motores",
    "MicroServo A0090": "servo motores",
    "Intel Edison": "arduinos",
    "Arduino Nano": "arduinos",
    "Arduino 101": "arduinos",
    "Arduino DUE": "arduinos",
    "Arduino Pro Mini": "arduinos",
    "Llantas Mecanum Lego": "mecanica",
    "Track & Wheel Set": "mecanica",
    "Garra": "mecanica",
    "Llantas Mecanum Rojas": "mecanica",
    "Acelerometro GY-61": "imu",
    "CMPS 11": "imu",
    "TCRT": "varios",
    "Sensor de Color": "varios",
    "ZX Gesture sensor": "varios",
    "Sound Detector": "varios",
    "Bluetooth Arduino": "varios",
    "TFTLCD Arduino Mega": "varios",
    "Switches": "electronica",
    "Potenciometros": "electronica",
    "Battery Jack": "electronica",
    "Boton": "electronica",
    "Portapilas AA": "electronica",
    "Conector XT": "electronica",
    "Broche Portapilas AA": "electronica",
    "Pila Lipo 11_1V 2200 mAh": "electronica",
    "Pila Lipo desconocida": "electronica",
    "Logic Level Converter": "electronica",
    "Regulador de Voltaje variable": "electronica",
    "BreadBoard power": "electronica",
    "LED RGB": "electronica",
    "Display 7 segmentos": "electronica",
}

export default Articulos